Attempt to improve compatibility with ChromeOS

diff --git a/linuxloops b/linuxloops
--- a/linuxloops
+++ b/linuxloops
@@ -15262,6 +15262,8 @@ if [ "${systemd_init}" == "Yes" ]; then
 	mount --make-slave /mnt/dev/console
 	ln -s /dev/null /mnt/etc/systemd/system/systemd-binfmt.service
 	ln -s /dev/null /mnt/etc/systemd/system/systemd-resolved.service
+    ln -s /dev/null /mnt/etc/systemd/system/connman.service
+    ln -s /dev/null /mnt/etc/systemd/system/NetworkManager.service
 	touch /tmp/pid_ns
 	sudo -b container=chroot unshare --pid=/tmp/pid_ns --fork --mount-proc --kill-child --root=/mnt /lib/systemd/systemd --unit=basic.target
 	sleep 30
@@ -15302,7 +15304,9 @@ if [ -f /tmp/linuxloops/install_bootloader ]; then \${chroot_cmd} /tmp/linuxloop
 if [ -f /tmp/linuxloops/install_custom_script ]; then \${chroot_cmd} /tmp/linuxloops/install_custom_script; fi
 if [ -f /tmp/linuxloops/cleanup ]; then \${chroot_cmd} /tmp/linuxloops/cleanup; fi
 if [ "${systemd_init}" == "Yes" ]; then
-	nsenter --pid=/tmp/pid_ns unshare --mount-proc --root=/mnt bash -c "rm /usr/sbin/policy-rc.d"
+	rm /mnt/usr/sbin/policy-rc.d
+    rm /mnt/etc/systemd/system/connman.service
+    rm /mnt/etc/systemd/system/NetworkManager.service
 	rm /mnt/etc/systemd/system/systemd-resolved.service
 	rm /mnt/etc/systemd/system/systemd-binfmt.service
 	umount /mnt/dev/console
@@ -17492,6 +17496,7 @@ fi
 if [ -b /dev/mapper/luks-"$(blkid -s UUID -o value "${root_partition}")" ]; then cryptsetup luksClose luks-"$(blkid -s UUID -o value "${root_partition}")"; fi
 if [ "${install_type}" == "image" ] && [ -b "${destination_device}" ]; then losetup -d "${destination_device}"; fi
 for removedir in "${linuxloopsdir}"/tmp/*; do if [ -d "${removedir}" ] && ! mountpoint -q "${removedir}"; then rm -rf "${removedir}"; fi; done
+if [ ! -z "${brunch}" ] || [ ! -z "${chromeos}" ]; then for removedir in /usr/local/tmp/linuxloops/*; do if [ -d "${removedir}" ] && ! mountpoint -q "${removedir}"; then rm -rf "${removedir}"; fi; done; fi
 if mountpoint -q "${linuxloopsdir}"/cache/iso/rootfs; then umount "${linuxloopsdir}"/cache/iso/rootfs; fi
 if mountpoint -q "${linuxloopsdir}"/cache/iso/level1; then umount "${linuxloopsdir}"/cache/iso/level1; fi
 if mountpoint -q "${linuxloopsdir}"/cache/iso/level2; then umount "${linuxloopsdir}"/cache/iso/level2; fi
@@ -17691,8 +17696,15 @@ bootstrap()
 {
 return_value=0
 if [ "${systemd_init}" == "Yes" ]; then
-	bootstrapdir="$(mktemp -d /tmp/linuxloops.XXXXXXXX)/bootstrap"
-	homebinddir="${linuxloopsdir}/tmp/$(echo ${bootstrapdir} | cut -d'/' -f3)"
+	if [ ! -z "${brunch}" ] || [ ! -z "${chromeos}" ]; then
+		mkdir -p /usr/local/tmp/linuxloops
+		chown 1000:1000 /usr/local/tmp /usr/local/tmp/linuxloops
+		homebinddir="$(sudo -u ${SUDO_USER} mktemp -d /usr/local/tmp/linuxloops/linuxloops.XXXXXXXX)"
+		bootstrapdir="${homebinddir}/bootstrap"
+	else
+		bootstrapdir="$(mktemp -d /tmp/linuxloops.XXXXXXXX)/bootstrap"
+		homebinddir="${linuxloopsdir}/tmp/$(echo ${bootstrapdir} | cut -d'/' -f3)"
+	fi
 	chrootdir="${bootstrapdir}"/mnt
 	trap 'end_bootstrap; clear -x; echo "Installation cancelled by INT or TERM signal."; exit 1' INT TERM
 	mkdir -p "${bootstrapdir}"
@@ -17703,8 +17715,15 @@ if [ "${systemd_init}" == "Yes" ]; then
 	mount --make-slave "${bootstrapdir}"
 	if ! mountpoint -q "${bootstrapdir}" || ! mountpoint -q "${homebinddir}" ; then echo "Linuxloops systemd init working directories could not be mounted."; exit 1; fi
 else
-	homebinddir="$(sudo -u ${SUDO_USER} mktemp -d ${linuxloopsdir}/tmp/linuxloops.XXXXXXXX)"
-	bootstrapdir="${homebinddir}/bootstrap"
+	if [ ! -z "${brunch}" ] || [ ! -z "${chromeos}" ]; then
+		mkdir -p /usr/local/tmp/linuxloops
+		chown 1000:1000 /usr/local/tmp /usr/local/tmp/linuxloops
+		homebinddir="$(sudo -u ${SUDO_USER} mktemp -d /usr/local/tmp/linuxloops/linuxloops.XXXXXXXX)"
+		bootstrapdir="${homebinddir}/bootstrap"
+	else
+		homebinddir="$(sudo -u ${SUDO_USER} mktemp -d ${linuxloopsdir}/tmp/linuxloops.XXXXXXXX)"
+		bootstrapdir="${homebinddir}/bootstrap"
+	fi
 	chrootdir="${bootstrapdir}"/mnt
 	trap 'end_bootstrap; clear -x; echo "Installation cancelled by INT or TERM signal."; exit 1' INT TERM
 	sudo -u ${SUDO_USER} mkdir -p "${bootstrapdir}"
@@ -17735,7 +17754,11 @@ mount -t tmpfs none "${bootstrapdir}"/run
 mount -t tmpfs -o mode=1777 none "${bootstrapdir}"/tmp
 mkdir -p "${bootstrapdir}"/tmp/linuxloops
 mount -t tmpfs -o mode=1777 none "${bootstrapdir}"/tmp/linuxloops
-cp /etc/hostname "${bootstrapdir}"/etc/hostname
+if [ -f /etc/hostname ]; then
+    cp /etc/hostname "${bootstrapdir}"/etc/hostname
+else
+    echo "bootstrap" > "${bootstrapdir}"/etc/hostname
+fi
 cp /etc/hosts "${bootstrapdir}"/etc/hosts
 rm -f "${bootstrapdir}"/etc/resolv.conf
 cp /etc/resolv.conf "${bootstrapdir}"/etc/resolv.conf
@@ -17926,7 +17949,7 @@ if [ ! -z "${chromeos}" ]; then
 	mkdir -p /mnt/stateful_partition/unencrypted/linuxloops_config/tmp
 	source=$(blkid --match-token LABEL=EFI-SYSTEM | head -1 | cut -d':' -f1)
 	mount "${source}" /mnt/stateful_partition/unencrypted/linuxloops_config/tmp
-	rm -rf /mnt/stateful_partition/unencrypted/linuxloops_config/tmp/*
+	rm -rf /mnt/stateful_partition/unencrypted/linuxloops_config/tmp/efi/boot
 	mkdir -p /mnt/stateful_partition/unencrypted/linuxloops_config/tmp/efi/boot
 	curl -L https://github.com/sebanc/brunch-unstable/raw/continuous-integration/efi-partition/efi/boot/grubx64.efi -o /mnt/stateful_partition/unencrypted/linuxloops_config/tmp/efi/boot/bootx64.efi
 	echo -e "set timeout=5\n"> /mnt/stateful_partition/unencrypted/linuxloops_config/tmp/efi/boot/grub.cfg
@@ -18066,6 +18089,7 @@ check_home_space()
 {
 find "${linuxloopsdir}"/cache/* -type f -mtime +7 -exec rm {} \; 2>/dev/null
 for removedir in "${linuxloopsdir}"/tmp/*; do if [ -d "${removedir}" ] && ! mountpoint -q "${removedir}"; then rm -rf "${removedir}"; fi; done
+if [ ! -z "${brunch}" ] || [ ! -z "${chromeos}" ]; then for removedir in /usr/local/tmp/linuxloops/*; do if [ -d "${removedir}" ] && ! mountpoint -q "${removedir}"; then rm -rf "${removedir}"; fi; done; fi
 case "${distribution}" in
 	'Bazzite')
 		available_space_needed=4
@@ -19661,7 +19685,7 @@ compute_partitions
 if [ ! $(list_array "available_locales" | grep -w "${locale}") ]; then echo "Locale ${locale} is not available, supported locales are:"; echo $(list_array "available_locales" | sed -e 's@\n@ @g'); exit 1; fi
 if [ ! $(list_array "available_keymaps" | grep -w "${keymap}") ]; then echo "Keymap ${keymap} is not available, supported keympas are:"; echo $(list_array "available_keymaps" | sed -e 's@\n@ @g'); exit 1; fi
 if [ ! $(list_array "available_timezones" | grep -w "${timezone}") ]; then echo "Timezone ${timezone} is not available, supported timezones are:"; echo $(list_array "available_timezones" | sed -e 's@\n@ @g'); exit 1; fi
-if [ -z "${chromeos}" ] && [ ! -z "${hostname}" ] && ! echo "${hostname}" | grep -Pq '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'; then echo "Provided hostname contains invalid characters."; exit 1; fi
+if [ ! -z "${chromeos}" ] && [ ! -z "${hostname}" ] && ! echo "${hostname}" | grep -Pq '^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$'; then echo "Provided hostname contains invalid characters."; exit 1; fi
 if [ "${root_fstype}" == "btrfs" ] && [ ! "${btrfs_supported}" == "Yes" ]; then echo "Filesystem type btrfs is not available for this distribution version."; exit 1; fi
 if [ "${nvidia}" == "Yes" ] && [ ! "${nvidia_supported}" == "Yes" ]; then echo "nvidia proprietary driver is not available for this distribution version."; exit 1; fi
 if [ "${surface}" == "Yes" ] && [ ! "${surface_supported}" == "Yes" ]; then echo "Surface patches are not available for this distribution version."; exit 1; fi
